export const VEHICLE_DIRECTIONS: Record<string, string> = {
  "S.P.1": "Girsu",
  "S.P.2": "Dir. General",
  "S.P.4": "Girsu",
  "S.P.5": "Girsu",
  "S.P.6": "Girsu",
  "S.P.7": "Dir. General",
  "S.P.8": "Serv. Pub.",
  "S.P.9": "Girsu",
  "S.P.10": "Serv. Pub.",
  "S.P.11": "Girsu",
  "S.P.12": "Serv. Pub.",

  "P.C.1": "Girsu",
  "P.C.2": "Girsu",
  "P.C.3": "Girsu",
  "P.C.4": "Girsu",
  "P.C.5": "Girsu",
  "P.C.6": "Girsu",

  "R.D.1": "Girsu",
  "R.D.2": "Girsu",
  "R.D.3": "Girsu",
  "R.D.4": "Girsu",
  "R.D.5": "Girsu",
  "R.D.6": "Girsu",
  "R.D.7": "Girsu",
  "R.D.8": "Girsu",
  "R.D.9": "Girsu",
  "R.D.10": "Girsu",

  "R.E. P.C.1": "Girsu",
  "R.E. P.C.2": "Girsu",
  "R.E. P.C.3": "Serv. Pub.",
  "R.E. P.C.4": "Girsu",
  "R.E. P.C.5": "Girsu",
  "R.E. P.C.6": "Girsu",
  "R.E. P.C.7": "Dir. General",
  "R.E. P.C.8": "Serv. Pub.",
  "R.E. P.C.9": "Girsu",
  "R.E. P.C.11": "Girsu",
  "R.E. P.C.12": "Girsu",

  "A.6": "Serv. Pub.",
  "B.P2": "Serv. Pub.",
  "B.P3": "Serv. Pub.",
  "B.P4": "Serv. Pub.",

  "B.2": "Serv. Pub.",
  "B.3": "Serv. Pub.",
  "B.4": "Serv. Pub.",
  "B.5": "Serv. Pub.",
  "B.6": "Serv. Pub.",
  "B.7": "Serv. Pub.",

  "BT.1": "Serv. Pub.",
  "BT.2": "Arbolado",
  "B.C1": "",

  "R.E. V.2": "Girsu",
  "R.E. V.3": "Girsu",
  "R.E. V.5": "Girsu",
  "R.E. V.6": "Girsu",
  "R.E. V.7": "Girsu",
  "R.E. V.8": "Serv. Pub.",
  "R.E. V.9": "Girsu",
  "R.E. V.10": "Girsu",
  "R.E. V.11": "Girsu",
  "R.E. V.12": "Girsu",
  "R.E. V.13": "Girsu",
  "R.E. V.14": "Girsu",

  "M.C. V.1": "Serv. Pub.",
  "M.C. P.R.1": "Serv. Pub.",

  "M.C.1": "Serv. Pub.",
  "M.C.2": "Serv. Pub.",
  "M.C.3": "Serv. Pub.",
  "M.C.4": "Serv. Pub.",
  "M.C.5": "Serv. Pub.",
  "M.C.6": "Serv. Pub.",

  "A.P.U.V.1": "Arbolado",
  "A.P.U.1": "Serv. Pub.",
  "A.P.U.2": "Arbolado",
  "A.P.U.3": "Arbolado",
  "A.P.U.4": "Arbolado",
  "A.P.U.5": "Arbolado",
  "A.P.U.6": "Arbolado",
  "A.P.U.7": "Arbolado",
  "A.P.U.8": "Arbolado",
  "A.P.U.9": "Arbolado",
  "A.P.U.10": "Dir. General",
  "A.P.U.11": "Arbolado",
  "A.P.U.12": "Arbolado",
  "A.P.U.13": "Arbolado",
  "A.P.U.14": "Arbolado",
  "A.P.U.16": "Arbolado",
  "A.P.U.17": "Arbolado",
  "A.P.U.18": "Arbolado",
  "Massey 2": "Arbolado",

  "A.1": "Girsu",
  "A.2": "Dir. General",
  "A.3": "Girsu",
  "A.4": "Dir. General",
  "A.5": "Girsu",
  "A.7": "Serv. Pub.",

  "G.A.1": "Dir. General",
  "G.A.2": "Dir. General",
  "G.A.3": "Dir. General",
  "G.A.4": "Dir. General",
  "G.A.5": "",

  "Z.V.1": "",
  "Z.V.2": "Zoo. y Vec.",

  "R.3": "Serv. Pub.",
  "R.4": "Serv. Pub.",
  "R.5": "Serv. Pub.",
  "R.6": "Serv. Pub.",
  "R.7": "Serv. Pub.",
  "R.8": "Serv. Pub.",
  "R.9": "Serv. Pub.",
  "R.10": "Serv. Pub.",
  "R.11": "Serv. Pub.",

  "I 1": "Dir. General",
  "I 2": "Dir. General",
  "I 3": "Dir. General",
  "I 4": "Dir. General",
};

export const getVehicleDirection = (vehicleCode: string) => {
  return VEHICLE_DIRECTIONS[String(vehicleCode || "").trim()] || "";
};